name: docs

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
              
    steps:
      - uses: actions/checkout@v2
        with:
<<<<<<< Updated upstream
          use-public-rspm: true
      
      - name: Install dependencies
        run: |
          install.packages(c("remotes","rcmdcheck"), repos = "https://cloud.r-project.org")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
=======
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
>>>>>>> Stashed changes

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./webpage/_site
